//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.ServiceReferenceUpdates {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUpdates.WebServiceUpdateSoap")]
    public interface WebServiceUpdateSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        ProjectMVC.ServiceReferenceUpdates.UpdateResponse Update(ProjectMVC.ServiceReferenceUpdates.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReferenceUpdates.UpdateResponse> UpdateAsync(ProjectMVC.ServiceReferenceUpdates.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReferenceUpdates.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(ProjectMVC.ServiceReferenceUpdates.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string telephone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string address;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(string name, string telephone, string email, string address) {
            this.name = name;
            this.telephone = telephone;
            this.email = email;
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReferenceUpdates.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(ProjectMVC.ServiceReferenceUpdates.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUpdateSoapChannel : ProjectMVC.ServiceReferenceUpdates.WebServiceUpdateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUpdateSoapClient : System.ServiceModel.ClientBase<ProjectMVC.ServiceReferenceUpdates.WebServiceUpdateSoap>, ProjectMVC.ServiceReferenceUpdates.WebServiceUpdateSoap {
        
        public WebServiceUpdateSoapClient() {
        }
        
        public WebServiceUpdateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUpdateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpdateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpdateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectMVC.ServiceReferenceUpdates.UpdateResponse ProjectMVC.ServiceReferenceUpdates.WebServiceUpdateSoap.Update(ProjectMVC.ServiceReferenceUpdates.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(string name, string telephone, string email, string address) {
            ProjectMVC.ServiceReferenceUpdates.UpdateRequest inValue = new ProjectMVC.ServiceReferenceUpdates.UpdateRequest();
            inValue.Body = new ProjectMVC.ServiceReferenceUpdates.UpdateRequestBody();
            inValue.Body.name = name;
            inValue.Body.telephone = telephone;
            inValue.Body.email = email;
            inValue.Body.address = address;
            ProjectMVC.ServiceReferenceUpdates.UpdateResponse retVal = ((ProjectMVC.ServiceReferenceUpdates.WebServiceUpdateSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReferenceUpdates.UpdateResponse> ProjectMVC.ServiceReferenceUpdates.WebServiceUpdateSoap.UpdateAsync(ProjectMVC.ServiceReferenceUpdates.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ServiceReferenceUpdates.UpdateResponse> UpdateAsync(string name, string telephone, string email, string address) {
            ProjectMVC.ServiceReferenceUpdates.UpdateRequest inValue = new ProjectMVC.ServiceReferenceUpdates.UpdateRequest();
            inValue.Body = new ProjectMVC.ServiceReferenceUpdates.UpdateRequestBody();
            inValue.Body.name = name;
            inValue.Body.telephone = telephone;
            inValue.Body.email = email;
            inValue.Body.address = address;
            return ((ProjectMVC.ServiceReferenceUpdates.WebServiceUpdateSoap)(this)).UpdateAsync(inValue);
        }
    }
}
