//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.ServiceReferenceIncrease {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceIncrease.WebServiceIncreaseSoap")]
    public interface WebServiceIncreaseSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Increase", ReplyAction="*")]
        void Increase(int toAccount, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Increase", ReplyAction="*")]
        System.Threading.Tasks.Task IncreaseAsync(int toAccount, int amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceIncreaseSoapChannel : ProjectMVC.ServiceReferenceIncrease.WebServiceIncreaseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceIncreaseSoapClient : System.ServiceModel.ClientBase<ProjectMVC.ServiceReferenceIncrease.WebServiceIncreaseSoap>, ProjectMVC.ServiceReferenceIncrease.WebServiceIncreaseSoap {
        
        public WebServiceIncreaseSoapClient() {
        }
        
        public WebServiceIncreaseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceIncreaseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceIncreaseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceIncreaseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Increase(int toAccount, int amount) {
            base.Channel.Increase(toAccount, amount);
        }
        
        public System.Threading.Tasks.Task IncreaseAsync(int toAccount, int amount) {
            return base.Channel.IncreaseAsync(toAccount, amount);
        }
    }
}
