//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.ServiceReferenceClients {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceClients.WebServiceClientSoap")]
    public interface WebServiceClientSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Client", ReplyAction="*")]
        ProjectMVC.ServiceReferenceClients.ClientResponse Client(ProjectMVC.ServiceReferenceClients.ClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Client", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReferenceClients.ClientResponse> ClientAsync(ProjectMVC.ServiceReferenceClients.ClientRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Client", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReferenceClients.ClientRequestBody Body;
        
        public ClientRequest() {
        }
        
        public ClientRequest(ProjectMVC.ServiceReferenceClients.ClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telephone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string question;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string answer;
        
        public ClientRequestBody() {
        }
        
        public ClientRequestBody(string name, string id, string email, string telephone, string address, string password, string question, string answer) {
            this.name = name;
            this.id = id;
            this.email = email;
            this.telephone = telephone;
            this.address = address;
            this.password = password;
            this.question = question;
            this.answer = answer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReferenceClients.ClientResponseBody Body;
        
        public ClientResponse() {
        }
        
        public ClientResponse(ProjectMVC.ServiceReferenceClients.ClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ClientResponseBody {
        
        public ClientResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceClientSoapChannel : ProjectMVC.ServiceReferenceClients.WebServiceClientSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClientSoapClient : System.ServiceModel.ClientBase<ProjectMVC.ServiceReferenceClients.WebServiceClientSoap>, ProjectMVC.ServiceReferenceClients.WebServiceClientSoap {
        
        public WebServiceClientSoapClient() {
        }
        
        public WebServiceClientSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClientSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClientSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClientSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectMVC.ServiceReferenceClients.ClientResponse ProjectMVC.ServiceReferenceClients.WebServiceClientSoap.Client(ProjectMVC.ServiceReferenceClients.ClientRequest request) {
            return base.Channel.Client(request);
        }
        
        public void Client(string name, string id, string email, string telephone, string address, string password, string question, string answer) {
            ProjectMVC.ServiceReferenceClients.ClientRequest inValue = new ProjectMVC.ServiceReferenceClients.ClientRequest();
            inValue.Body = new ProjectMVC.ServiceReferenceClients.ClientRequestBody();
            inValue.Body.name = name;
            inValue.Body.id = id;
            inValue.Body.email = email;
            inValue.Body.telephone = telephone;
            inValue.Body.address = address;
            inValue.Body.password = password;
            inValue.Body.question = question;
            inValue.Body.answer = answer;
            ProjectMVC.ServiceReferenceClients.ClientResponse retVal = ((ProjectMVC.ServiceReferenceClients.WebServiceClientSoap)(this)).Client(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReferenceClients.ClientResponse> ProjectMVC.ServiceReferenceClients.WebServiceClientSoap.ClientAsync(ProjectMVC.ServiceReferenceClients.ClientRequest request) {
            return base.Channel.ClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ServiceReferenceClients.ClientResponse> ClientAsync(string name, string id, string email, string telephone, string address, string password, string question, string answer) {
            ProjectMVC.ServiceReferenceClients.ClientRequest inValue = new ProjectMVC.ServiceReferenceClients.ClientRequest();
            inValue.Body = new ProjectMVC.ServiceReferenceClients.ClientRequestBody();
            inValue.Body.name = name;
            inValue.Body.id = id;
            inValue.Body.email = email;
            inValue.Body.telephone = telephone;
            inValue.Body.address = address;
            inValue.Body.password = password;
            inValue.Body.question = question;
            inValue.Body.answer = answer;
            return ((ProjectMVC.ServiceReferenceClients.WebServiceClientSoap)(this)).ClientAsync(inValue);
        }
    }
}
