//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.ServiceReferenceIncreases {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceIncreases.WebServiceIncreasesSoap")]
    public interface WebServiceIncreasesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Increase", ReplyAction="*")]
        void Increase(int toAccount, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Increase", ReplyAction="*")]
        System.Threading.Tasks.Task IncreaseAsync(int toAccount, int amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceIncreasesSoapChannel : ProjectMVC.ServiceReferenceIncreases.WebServiceIncreasesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceIncreasesSoapClient : System.ServiceModel.ClientBase<ProjectMVC.ServiceReferenceIncreases.WebServiceIncreasesSoap>, ProjectMVC.ServiceReferenceIncreases.WebServiceIncreasesSoap {
        
        public WebServiceIncreasesSoapClient() {
        }
        
        public WebServiceIncreasesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceIncreasesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceIncreasesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceIncreasesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Increase(int toAccount, int amount) {
            base.Channel.Increase(toAccount, amount);
        }
        
        public System.Threading.Tasks.Task IncreaseAsync(int toAccount, int amount) {
            return base.Channel.IncreaseAsync(toAccount, amount);
        }
    }
}
