//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.ServiceReferenceTransaction2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTransaction2.WebServiceTransactionSoap")]
    public interface WebServiceTransactionSoap {
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTransaction", ReplyAction="*")]
        ProjectMVC.ServiceReferenceTransaction2.AddTransactionResponse AddTransaction(ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReferenceTransaction2.AddTransactionResponse> AddTransactionAsync(ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTransaction", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequestBody Body;
        
        public AddTransactionRequest() {
        }
        
        public AddTransactionRequest(ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int toAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int fromAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string user;
        
        public AddTransactionRequestBody() {
        }
        
        public AddTransactionRequestBody(int toAccount, int fromAccount, int amount, string date, string user) {
            this.toAccount = toAccount;
            this.fromAccount = fromAccount;
            this.amount = amount;
            this.date = date;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReferenceTransaction2.AddTransactionResponseBody Body;
        
        public AddTransactionResponse() {
        }
        
        public AddTransactionResponse(ProjectMVC.ServiceReferenceTransaction2.AddTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddTransactionResponseBody {
        
        public AddTransactionResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTransactionSoapChannel : ProjectMVC.ServiceReferenceTransaction2.WebServiceTransactionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTransactionSoapClient : System.ServiceModel.ClientBase<ProjectMVC.ServiceReferenceTransaction2.WebServiceTransactionSoap>, ProjectMVC.ServiceReferenceTransaction2.WebServiceTransactionSoap {
        
        public WebServiceTransactionSoapClient() {
        }
        
        public WebServiceTransactionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTransactionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTransactionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTransactionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectMVC.ServiceReferenceTransaction2.AddTransactionResponse ProjectMVC.ServiceReferenceTransaction2.WebServiceTransactionSoap.AddTransaction(ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequest request) {
            return base.Channel.AddTransaction(request);
        }
        
        public void AddTransaction(int toAccount, int fromAccount, int amount, string date, string user) {
            ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequest inValue = new ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequest();
            inValue.Body = new ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequestBody();
            inValue.Body.toAccount = toAccount;
            inValue.Body.fromAccount = fromAccount;
            inValue.Body.amount = amount;
            inValue.Body.date = date;
            inValue.Body.user = user;
            ProjectMVC.ServiceReferenceTransaction2.AddTransactionResponse retVal = ((ProjectMVC.ServiceReferenceTransaction2.WebServiceTransactionSoap)(this)).AddTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReferenceTransaction2.AddTransactionResponse> ProjectMVC.ServiceReferenceTransaction2.WebServiceTransactionSoap.AddTransactionAsync(ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequest request) {
            return base.Channel.AddTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ServiceReferenceTransaction2.AddTransactionResponse> AddTransactionAsync(int toAccount, int fromAccount, int amount, string date, string user) {
            ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequest inValue = new ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequest();
            inValue.Body = new ProjectMVC.ServiceReferenceTransaction2.AddTransactionRequestBody();
            inValue.Body.toAccount = toAccount;
            inValue.Body.fromAccount = fromAccount;
            inValue.Body.amount = amount;
            inValue.Body.date = date;
            inValue.Body.user = user;
            return ((ProjectMVC.ServiceReferenceTransaction2.WebServiceTransactionSoap)(this)).AddTransactionAsync(inValue);
        }
    }
}
