//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.ServiceReferenceToAccount {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceToAccount.WebServiceToAccountSoap")]
    public interface WebServiceToAccountSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToAccountBalance", ReplyAction="*")]
        int ToAccountBalance(int account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToAccountBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ToAccountBalanceAsync(int account);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceToAccountSoapChannel : ProjectMVC.ServiceReferenceToAccount.WebServiceToAccountSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceToAccountSoapClient : System.ServiceModel.ClientBase<ProjectMVC.ServiceReferenceToAccount.WebServiceToAccountSoap>, ProjectMVC.ServiceReferenceToAccount.WebServiceToAccountSoap {
        
        public WebServiceToAccountSoapClient() {
        }
        
        public WebServiceToAccountSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceToAccountSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceToAccountSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceToAccountSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ToAccountBalance(int account) {
            return base.Channel.ToAccountBalance(account);
        }
        
        public System.Threading.Tasks.Task<int> ToAccountBalanceAsync(int account) {
            return base.Channel.ToAccountBalanceAsync(account);
        }
    }
}
