//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.BilionBankWebServiceSoap")]
    public interface BilionBankWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Client", ReplyAction="*")]
        ProjectMVC.ServiceReference4.ClientResponse Client(ProjectMVC.ServiceReference4.ClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Client", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.ClientResponse> ClientAsync(ProjectMVC.ServiceReference4.ClientRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account", ReplyAction="*")]
        ProjectMVC.ServiceReference4.AccountResponse Account(ProjectMVC.ServiceReference4.AccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.AccountResponse> AccountAsync(ProjectMVC.ServiceReference4.AccountRequest request);
        
        // CODEGEN: Generating message contract since element name toAccount from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTransaction", ReplyAction="*")]
        ProjectMVC.ServiceReference4.AddTransactionResponse AddTransaction(ProjectMVC.ServiceReference4.AddTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.AddTransactionResponse> AddTransactionAsync(ProjectMVC.ServiceReference4.AddTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name toAccount from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deduct", ReplyAction="*")]
        ProjectMVC.ServiceReference4.DeductResponse Deduct(ProjectMVC.ServiceReference4.DeductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deduct", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.DeductResponse> DeductAsync(ProjectMVC.ServiceReference4.DeductRequest request);
        
        // CODEGEN: Generating message contract since element name toAccount from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Increase", ReplyAction="*")]
        ProjectMVC.ServiceReference4.IncreaseResponse Increase(ProjectMVC.ServiceReference4.IncreaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Increase", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.IncreaseResponse> IncreaseAsync(ProjectMVC.ServiceReference4.IncreaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Client", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference4.ClientRequestBody Body;
        
        public ClientRequest() {
        }
        
        public ClientRequest(ProjectMVC.ServiceReference4.ClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telephone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string question;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string answer;
        
        public ClientRequestBody() {
        }
        
        public ClientRequestBody(string name, long id, string email, string telephone, string address, string password, string question, string answer) {
            this.name = name;
            this.id = id;
            this.email = email;
            this.telephone = telephone;
            this.address = address;
            this.password = password;
            this.question = question;
            this.answer = answer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference4.ClientResponseBody Body;
        
        public ClientResponse() {
        }
        
        public ClientResponse(ProjectMVC.ServiceReference4.ClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ClientResponseBody {
        
        public ClientResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Account", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference4.AccountRequestBody Body;
        
        public AccountRequest() {
        }
        
        public AccountRequest(ProjectMVC.ServiceReference4.AccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int balance;
        
        public AccountRequestBody() {
        }
        
        public AccountRequestBody(int accountNumber, string name, string date, int balance) {
            this.accountNumber = accountNumber;
            this.name = name;
            this.date = date;
            this.balance = balance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference4.AccountResponseBody Body;
        
        public AccountResponse() {
        }
        
        public AccountResponse(ProjectMVC.ServiceReference4.AccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AccountResponseBody {
        
        public AccountResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTransaction", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference4.AddTransactionRequestBody Body;
        
        public AddTransactionRequest() {
        }
        
        public AddTransactionRequest(ProjectMVC.ServiceReference4.AddTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fromAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string date;
        
        public AddTransactionRequestBody() {
        }
        
        public AddTransactionRequestBody(string toAccount, string fromAccount, int amount, string date) {
            this.toAccount = toAccount;
            this.fromAccount = fromAccount;
            this.amount = amount;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference4.AddTransactionResponseBody Body;
        
        public AddTransactionResponse() {
        }
        
        public AddTransactionResponse(ProjectMVC.ServiceReference4.AddTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddTransactionResponseBody {
        
        public AddTransactionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Deduct", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference4.DeductRequestBody Body;
        
        public DeductRequest() {
        }
        
        public DeductRequest(ProjectMVC.ServiceReference4.DeductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fromAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string date;
        
        public DeductRequestBody() {
        }
        
        public DeductRequestBody(string toAccount, string fromAccount, int amount, string date) {
            this.toAccount = toAccount;
            this.fromAccount = fromAccount;
            this.amount = amount;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeductResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference4.DeductResponseBody Body;
        
        public DeductResponse() {
        }
        
        public DeductResponse(ProjectMVC.ServiceReference4.DeductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeductResponseBody {
        
        public DeductResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncreaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Increase", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference4.IncreaseRequestBody Body;
        
        public IncreaseRequest() {
        }
        
        public IncreaseRequest(ProjectMVC.ServiceReference4.IncreaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IncreaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fromAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string date;
        
        public IncreaseRequestBody() {
        }
        
        public IncreaseRequestBody(string toAccount, string fromAccount, int amount, string date) {
            this.toAccount = toAccount;
            this.fromAccount = fromAccount;
            this.amount = amount;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncreaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IncreaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference4.IncreaseResponseBody Body;
        
        public IncreaseResponse() {
        }
        
        public IncreaseResponse(ProjectMVC.ServiceReference4.IncreaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class IncreaseResponseBody {
        
        public IncreaseResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BilionBankWebServiceSoapChannel : ProjectMVC.ServiceReference4.BilionBankWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BilionBankWebServiceSoapClient : System.ServiceModel.ClientBase<ProjectMVC.ServiceReference4.BilionBankWebServiceSoap>, ProjectMVC.ServiceReference4.BilionBankWebServiceSoap {
        
        public BilionBankWebServiceSoapClient() {
        }
        
        public BilionBankWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BilionBankWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BilionBankWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BilionBankWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectMVC.ServiceReference4.ClientResponse ProjectMVC.ServiceReference4.BilionBankWebServiceSoap.Client(ProjectMVC.ServiceReference4.ClientRequest request) {
            return base.Channel.Client(request);
        }
        
        public void Client(string name, long id, string email, string telephone, string address, string password, string question, string answer) {
            ProjectMVC.ServiceReference4.ClientRequest inValue = new ProjectMVC.ServiceReference4.ClientRequest();
            inValue.Body = new ProjectMVC.ServiceReference4.ClientRequestBody();
            inValue.Body.name = name;
            inValue.Body.id = id;
            inValue.Body.email = email;
            inValue.Body.telephone = telephone;
            inValue.Body.address = address;
            inValue.Body.password = password;
            inValue.Body.question = question;
            inValue.Body.answer = answer;
            ProjectMVC.ServiceReference4.ClientResponse retVal = ((ProjectMVC.ServiceReference4.BilionBankWebServiceSoap)(this)).Client(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.ClientResponse> ProjectMVC.ServiceReference4.BilionBankWebServiceSoap.ClientAsync(ProjectMVC.ServiceReference4.ClientRequest request) {
            return base.Channel.ClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.ClientResponse> ClientAsync(string name, long id, string email, string telephone, string address, string password, string question, string answer) {
            ProjectMVC.ServiceReference4.ClientRequest inValue = new ProjectMVC.ServiceReference4.ClientRequest();
            inValue.Body = new ProjectMVC.ServiceReference4.ClientRequestBody();
            inValue.Body.name = name;
            inValue.Body.id = id;
            inValue.Body.email = email;
            inValue.Body.telephone = telephone;
            inValue.Body.address = address;
            inValue.Body.password = password;
            inValue.Body.question = question;
            inValue.Body.answer = answer;
            return ((ProjectMVC.ServiceReference4.BilionBankWebServiceSoap)(this)).ClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectMVC.ServiceReference4.AccountResponse ProjectMVC.ServiceReference4.BilionBankWebServiceSoap.Account(ProjectMVC.ServiceReference4.AccountRequest request) {
            return base.Channel.Account(request);
        }
        
        public void Account(int accountNumber, string name, string date, int balance) {
            ProjectMVC.ServiceReference4.AccountRequest inValue = new ProjectMVC.ServiceReference4.AccountRequest();
            inValue.Body = new ProjectMVC.ServiceReference4.AccountRequestBody();
            inValue.Body.accountNumber = accountNumber;
            inValue.Body.name = name;
            inValue.Body.date = date;
            inValue.Body.balance = balance;
            ProjectMVC.ServiceReference4.AccountResponse retVal = ((ProjectMVC.ServiceReference4.BilionBankWebServiceSoap)(this)).Account(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.AccountResponse> ProjectMVC.ServiceReference4.BilionBankWebServiceSoap.AccountAsync(ProjectMVC.ServiceReference4.AccountRequest request) {
            return base.Channel.AccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.AccountResponse> AccountAsync(int accountNumber, string name, string date, int balance) {
            ProjectMVC.ServiceReference4.AccountRequest inValue = new ProjectMVC.ServiceReference4.AccountRequest();
            inValue.Body = new ProjectMVC.ServiceReference4.AccountRequestBody();
            inValue.Body.accountNumber = accountNumber;
            inValue.Body.name = name;
            inValue.Body.date = date;
            inValue.Body.balance = balance;
            return ((ProjectMVC.ServiceReference4.BilionBankWebServiceSoap)(this)).AccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectMVC.ServiceReference4.AddTransactionResponse ProjectMVC.ServiceReference4.BilionBankWebServiceSoap.AddTransaction(ProjectMVC.ServiceReference4.AddTransactionRequest request) {
            return base.Channel.AddTransaction(request);
        }
        
        public void AddTransaction(string toAccount, string fromAccount, int amount, string date) {
            ProjectMVC.ServiceReference4.AddTransactionRequest inValue = new ProjectMVC.ServiceReference4.AddTransactionRequest();
            inValue.Body = new ProjectMVC.ServiceReference4.AddTransactionRequestBody();
            inValue.Body.toAccount = toAccount;
            inValue.Body.fromAccount = fromAccount;
            inValue.Body.amount = amount;
            inValue.Body.date = date;
            ProjectMVC.ServiceReference4.AddTransactionResponse retVal = ((ProjectMVC.ServiceReference4.BilionBankWebServiceSoap)(this)).AddTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.AddTransactionResponse> ProjectMVC.ServiceReference4.BilionBankWebServiceSoap.AddTransactionAsync(ProjectMVC.ServiceReference4.AddTransactionRequest request) {
            return base.Channel.AddTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.AddTransactionResponse> AddTransactionAsync(string toAccount, string fromAccount, int amount, string date) {
            ProjectMVC.ServiceReference4.AddTransactionRequest inValue = new ProjectMVC.ServiceReference4.AddTransactionRequest();
            inValue.Body = new ProjectMVC.ServiceReference4.AddTransactionRequestBody();
            inValue.Body.toAccount = toAccount;
            inValue.Body.fromAccount = fromAccount;
            inValue.Body.amount = amount;
            inValue.Body.date = date;
            return ((ProjectMVC.ServiceReference4.BilionBankWebServiceSoap)(this)).AddTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectMVC.ServiceReference4.DeductResponse ProjectMVC.ServiceReference4.BilionBankWebServiceSoap.Deduct(ProjectMVC.ServiceReference4.DeductRequest request) {
            return base.Channel.Deduct(request);
        }
        
        public void Deduct(string toAccount, string fromAccount, int amount, string date) {
            ProjectMVC.ServiceReference4.DeductRequest inValue = new ProjectMVC.ServiceReference4.DeductRequest();
            inValue.Body = new ProjectMVC.ServiceReference4.DeductRequestBody();
            inValue.Body.toAccount = toAccount;
            inValue.Body.fromAccount = fromAccount;
            inValue.Body.amount = amount;
            inValue.Body.date = date;
            ProjectMVC.ServiceReference4.DeductResponse retVal = ((ProjectMVC.ServiceReference4.BilionBankWebServiceSoap)(this)).Deduct(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.DeductResponse> ProjectMVC.ServiceReference4.BilionBankWebServiceSoap.DeductAsync(ProjectMVC.ServiceReference4.DeductRequest request) {
            return base.Channel.DeductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.DeductResponse> DeductAsync(string toAccount, string fromAccount, int amount, string date) {
            ProjectMVC.ServiceReference4.DeductRequest inValue = new ProjectMVC.ServiceReference4.DeductRequest();
            inValue.Body = new ProjectMVC.ServiceReference4.DeductRequestBody();
            inValue.Body.toAccount = toAccount;
            inValue.Body.fromAccount = fromAccount;
            inValue.Body.amount = amount;
            inValue.Body.date = date;
            return ((ProjectMVC.ServiceReference4.BilionBankWebServiceSoap)(this)).DeductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectMVC.ServiceReference4.IncreaseResponse ProjectMVC.ServiceReference4.BilionBankWebServiceSoap.Increase(ProjectMVC.ServiceReference4.IncreaseRequest request) {
            return base.Channel.Increase(request);
        }
        
        public void Increase(string toAccount, string fromAccount, int amount, string date) {
            ProjectMVC.ServiceReference4.IncreaseRequest inValue = new ProjectMVC.ServiceReference4.IncreaseRequest();
            inValue.Body = new ProjectMVC.ServiceReference4.IncreaseRequestBody();
            inValue.Body.toAccount = toAccount;
            inValue.Body.fromAccount = fromAccount;
            inValue.Body.amount = amount;
            inValue.Body.date = date;
            ProjectMVC.ServiceReference4.IncreaseResponse retVal = ((ProjectMVC.ServiceReference4.BilionBankWebServiceSoap)(this)).Increase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.IncreaseResponse> ProjectMVC.ServiceReference4.BilionBankWebServiceSoap.IncreaseAsync(ProjectMVC.ServiceReference4.IncreaseRequest request) {
            return base.Channel.IncreaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ServiceReference4.IncreaseResponse> IncreaseAsync(string toAccount, string fromAccount, int amount, string date) {
            ProjectMVC.ServiceReference4.IncreaseRequest inValue = new ProjectMVC.ServiceReference4.IncreaseRequest();
            inValue.Body = new ProjectMVC.ServiceReference4.IncreaseRequestBody();
            inValue.Body.toAccount = toAccount;
            inValue.Body.fromAccount = fromAccount;
            inValue.Body.amount = amount;
            inValue.Body.date = date;
            return ((ProjectMVC.ServiceReference4.BilionBankWebServiceSoap)(this)).IncreaseAsync(inValue);
        }
    }
}
