//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BilionBankWebServiceSoap")]
    public interface BilionBankWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Client", ReplyAction="*")]
        ProjectMVC.ServiceReference1.ClientResponse Client(ProjectMVC.ServiceReference1.ClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Client", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference1.ClientResponse> ClientAsync(ProjectMVC.ServiceReference1.ClientRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account", ReplyAction="*")]
        ProjectMVC.ServiceReference1.AccountResponse Account(ProjectMVC.ServiceReference1.AccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference1.AccountResponse> AccountAsync(ProjectMVC.ServiceReference1.AccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Client", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference1.ClientRequestBody Body;
        
        public ClientRequest() {
        }
        
        public ClientRequest(ProjectMVC.ServiceReference1.ClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telephone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string question;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string answer;
        
        public ClientRequestBody() {
        }
        
        public ClientRequestBody(string name, long id, string email, string telephone, string address, string password, string question, string answer) {
            this.name = name;
            this.id = id;
            this.email = email;
            this.telephone = telephone;
            this.address = address;
            this.password = password;
            this.question = question;
            this.answer = answer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference1.ClientResponseBody Body;
        
        public ClientResponse() {
        }
        
        public ClientResponse(ProjectMVC.ServiceReference1.ClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ClientResult;
        
        public ClientResponseBody() {
        }
        
        public ClientResponseBody(string ClientResult) {
            this.ClientResult = ClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Account", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference1.AccountRequestBody Body;
        
        public AccountRequest() {
        }
        
        public AccountRequest(ProjectMVC.ServiceReference1.AccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int balance;
        
        public AccountRequestBody() {
        }
        
        public AccountRequestBody(int accountNumber, string name, string date, int balance) {
            this.accountNumber = accountNumber;
            this.name = name;
            this.date = date;
            this.balance = balance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectMVC.ServiceReference1.AccountResponseBody Body;
        
        public AccountResponse() {
        }
        
        public AccountResponse(ProjectMVC.ServiceReference1.AccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AccountResult;
        
        public AccountResponseBody() {
        }
        
        public AccountResponseBody(string AccountResult) {
            this.AccountResult = AccountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BilionBankWebServiceSoapChannel : ProjectMVC.ServiceReference1.BilionBankWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BilionBankWebServiceSoapClient : System.ServiceModel.ClientBase<ProjectMVC.ServiceReference1.BilionBankWebServiceSoap>, ProjectMVC.ServiceReference1.BilionBankWebServiceSoap {
        
        public BilionBankWebServiceSoapClient() {
        }
        
        public BilionBankWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BilionBankWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BilionBankWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BilionBankWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectMVC.ServiceReference1.ClientResponse ProjectMVC.ServiceReference1.BilionBankWebServiceSoap.Client(ProjectMVC.ServiceReference1.ClientRequest request) {
            return base.Channel.Client(request);
        }
        
        public string Client(string name, long id, string email, string telephone, string address, string password, string question, string answer) {
            ProjectMVC.ServiceReference1.ClientRequest inValue = new ProjectMVC.ServiceReference1.ClientRequest();
            inValue.Body = new ProjectMVC.ServiceReference1.ClientRequestBody();
            inValue.Body.name = name;
            inValue.Body.id = id;
            inValue.Body.email = email;
            inValue.Body.telephone = telephone;
            inValue.Body.address = address;
            inValue.Body.password = password;
            inValue.Body.question = question;
            inValue.Body.answer = answer;
            ProjectMVC.ServiceReference1.ClientResponse retVal = ((ProjectMVC.ServiceReference1.BilionBankWebServiceSoap)(this)).Client(inValue);
            return retVal.Body.ClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference1.ClientResponse> ProjectMVC.ServiceReference1.BilionBankWebServiceSoap.ClientAsync(ProjectMVC.ServiceReference1.ClientRequest request) {
            return base.Channel.ClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ServiceReference1.ClientResponse> ClientAsync(string name, long id, string email, string telephone, string address, string password, string question, string answer) {
            ProjectMVC.ServiceReference1.ClientRequest inValue = new ProjectMVC.ServiceReference1.ClientRequest();
            inValue.Body = new ProjectMVC.ServiceReference1.ClientRequestBody();
            inValue.Body.name = name;
            inValue.Body.id = id;
            inValue.Body.email = email;
            inValue.Body.telephone = telephone;
            inValue.Body.address = address;
            inValue.Body.password = password;
            inValue.Body.question = question;
            inValue.Body.answer = answer;
            return ((ProjectMVC.ServiceReference1.BilionBankWebServiceSoap)(this)).ClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectMVC.ServiceReference1.AccountResponse ProjectMVC.ServiceReference1.BilionBankWebServiceSoap.Account(ProjectMVC.ServiceReference1.AccountRequest request) {
            return base.Channel.Account(request);
        }
        
        public string Account(int accountNumber, string name, string date, int balance) {
            ProjectMVC.ServiceReference1.AccountRequest inValue = new ProjectMVC.ServiceReference1.AccountRequest();
            inValue.Body = new ProjectMVC.ServiceReference1.AccountRequestBody();
            inValue.Body.accountNumber = accountNumber;
            inValue.Body.name = name;
            inValue.Body.date = date;
            inValue.Body.balance = balance;
            ProjectMVC.ServiceReference1.AccountResponse retVal = ((ProjectMVC.ServiceReference1.BilionBankWebServiceSoap)(this)).Account(inValue);
            return retVal.Body.AccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectMVC.ServiceReference1.AccountResponse> ProjectMVC.ServiceReference1.BilionBankWebServiceSoap.AccountAsync(ProjectMVC.ServiceReference1.AccountRequest request) {
            return base.Channel.AccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ServiceReference1.AccountResponse> AccountAsync(int accountNumber, string name, string date, int balance) {
            ProjectMVC.ServiceReference1.AccountRequest inValue = new ProjectMVC.ServiceReference1.AccountRequest();
            inValue.Body = new ProjectMVC.ServiceReference1.AccountRequestBody();
            inValue.Body.accountNumber = accountNumber;
            inValue.Body.name = name;
            inValue.Body.date = date;
            inValue.Body.balance = balance;
            return ((ProjectMVC.ServiceReference1.BilionBankWebServiceSoap)(this)).AccountAsync(inValue);
        }
    }
}
