//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.ServiceReferenceDeduct {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDeduct.WebServiceDeductSoap")]
    public interface WebServiceDeductSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deduct", ReplyAction="*")]
        void Deduct(int fromAccount, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deduct", ReplyAction="*")]
        System.Threading.Tasks.Task DeductAsync(int fromAccount, int amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceDeductSoapChannel : ProjectMVC.ServiceReferenceDeduct.WebServiceDeductSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceDeductSoapClient : System.ServiceModel.ClientBase<ProjectMVC.ServiceReferenceDeduct.WebServiceDeductSoap>, ProjectMVC.ServiceReferenceDeduct.WebServiceDeductSoap {
        
        public WebServiceDeductSoapClient() {
        }
        
        public WebServiceDeductSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceDeductSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDeductSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDeductSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Deduct(int fromAccount, int amount) {
            base.Channel.Deduct(fromAccount, amount);
        }
        
        public System.Threading.Tasks.Task DeductAsync(int fromAccount, int amount) {
            return base.Channel.DeductAsync(fromAccount, amount);
        }
    }
}
